export const PERSON_REPOSITORY = 'PERSON_REPOSITORY';
export const COMMUNITY_HALL_REPOSITORY = 'COMMUNITY_HALL_REPOSITORY';
export const MANAGEMENT_COMMITTEE_REPOSITORY = 'MANAGEMENT_COMMITTEE_REPOSITORY';
export const CHILD_REPOSITORY = 'CHILD_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const AUTH_SERVICE = 'AUTH_SERVICE';