export const PERSON_REPOSITORY = 'PERSON_REPOSITORY';
export const COMMUNITY_HALL_REPOSITORY = 'COMMUNITY_HALL_REPOSITORY';
export const COMMITTEE_MEMBERSHIP_REPOSITORY =
  'COMMITTEE_MEMBERSHIP_REPOSITORY';
export const CHILD_REPOSITORY = 'CHILD_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const CHILD_EXCEL_READER = 'CHILD_EXCEL_READER';
export const ALERT_CHILD_REPOSITORY = 'ALERT_CHILD_REPOSITORY';
export const SESSION_REPOSITORY = 'SESSION_REPOSITORY';
export const COMMITTEE_REPOSITORY = 'COMMITTEE_REPOSITORY';
export const AUDIT_EVENT_REPOSITORY = 'AUDIT_EVENT_REPOSITORY';
export const CHILD_HISTORY_REPOSITORY = 'CHILD_HISTORY_REPOSITORY';
export const IMPORT_ERROR_LOG_REPOSITORY = 'IMPORT_ERROR_LOG_REPOSITORY';
export const CAREGIVER_MOTHER_REPOSITORY = 'CAREGIVER_MOTHER_REPOSITORY';
export const CAREGIVER_HALL_ASSIGNMENT_REPOSITORY =
  'CAREGIVER_HALL_ASSIGNMENT_REPOSITORY';
export const CAREGIVER_SCHEDULE_REPOSITORY = 'CAREGIVER_SCHEDULE_REPOSITORY';
export const CAREGIVER_ATTENDANCE_REPOSITORY =
  'CAREGIVER_ATTENDANCE_REPOSITORY';
export const CAREGIVER_ATTENDANCE_EXCEPTION_REPOSITORY =
  'CAREGIVER_ATTENDANCE_EXCEPTION_REPOSITORY';
export const CAREGIVER_ATTENDANCE_EVENT_REPOSITORY =
  'CAREGIVER_ATTENDANCE_EVENT_REPOSITORY';
